###################################################
#                                                 #
#                 DEFAULT CONFIG                  #
#                                                 #
###################################################
default_config:
system_health:
lovelace:
  mode: yaml


############
#   SSL    #
############

http:
  base_url: !secret baseurl 
  ssl_certificate: /ssl/fullchain.pem
  ssl_key: /ssl/privkey.pem
  
google_assistant:
  project_id: !secret homeid 
  api_key: !secret apigoogle 
  exposed_domains:
    - switch
    - light
    - group
    - script
    - climate 

############
# RECORDER #
############

recorder:
  purge_keep_days: 5 # Only 5 days
  include: # only include following domains:
    domains:
      - climate
      - sensor
      - person
      
# Text to speech
tts:
  - platform: google_translate      
      
###################################################
#                                                 #
#                 BREAK UP CONFIG                 #
#                                                 #
###################################################

group: !include groups.yaml
automation: !include automations.yaml
script: !include scripts.yaml
light: !include light.yaml
input_boolean: !include input_boolean.yaml
input_number: !include input_number.yaml
sensor: !include sensor.yaml
scene: !include scenes.yaml
    

###################################################
#                                                 #
#                   PRODUCTS                      #
#                                                 #
###################################################

##       RING DEURBEL

ring:
  username: !secret email
  password: !secret ring 
  scan_interval: 2

binary_sensor:
  - platform: ring
  - platform: huesensor

ffmpeg:    

camera: 
  - platform: ring  
  
##       SONOF 

sonoff:
  username: !secret email 
  password: !secret sonof 
  scan_interval: 60
  grace_period: 600
  api_region: 'eu'
  entity_prefix: True
  debug: False

## HARMONY

remote:
  - platform: harmony
    name: tvwoonkamer
    host: 192.168.178.24

##  VACUUM

vacuum:
  - platform: xiaomi_miio
    host: 192.168.178.60
    token: !secret token
    name: frits

    



      
