## 
# PURGE
# BACKUP
# SECRETS
# HOME ASSIST
# Huis verlaten!!<<<<<<<<<<<<<<<


############
# RECORDER #
############

recorder:
  purge_keep_days: 5 # Only 5 days
  include: # only include following domains:
    domains:
      - climate
      - sensor
      - person
      
############
# NOTIFY   #
############

notify:
  - name: NOTIFIER_NAME
    platform: telegram
    chat_id: !secret chatid    

telegram_bot:
  - platform: polling
    api_key: !secret api 
    allowed_chat_ids:
      - !secret chatid

input_boolean:
  slaapstart:
    name: Slaap aanzetten
    initial: off
    icon: mdi:bed
  check4:
    name: check4
    initial: off    
    
###################################################
#                                                 #
#                 DEFAULT CONFIG                  #
#                                                 #
###################################################
default_config:

lovelace:
  mode: yaml

###################################################
#                                                 #
#                 BREAK UP CONFIG                 #
#                                                 #
###################################################

group: !include groups.yaml
automation: !include automations.yaml
script: !include scripts.yaml
light: !include light.yaml

# Text to speech
tts:
  - platform: google_translate


###################################################
#                                                 #
#                   PRODUCTS                      #
#                                                 #
###################################################

##       RING DEURBEL


ring:
  username: !secret email
  password: !secret ring 
  scan_interval: 2

binary_sensor:
  - platform: ring
  - platform: huesensor

ffmpeg:    

camera: 
  - platform: ring  
  
##       SONOF INSTELLEN

sonoff:
  username: !secret email 
  password: !secret sonof 
  scan_interval: 60
  grace_period: 600
  api_region: 'eu'
  entity_prefix: True
  debug: False

## HARMONY


remote:
  - platform: harmony
    name: tvwoonkamer
    host: 192.168.178.24


##  SENSORS

sensor:

- platform: systemmonitor
  resources:
    - type: disk_use_percent
      arg: /home
    - type: memory_free
  
- platform: afvalwijzer
  postcode: !secret postcode
  huisnummer: !secret huisnummer
  

- platform: template
  sensors:
    woonkamer_tv:
      friendly_name: 'woonkamer'     
      value_template: "{{ state_attr('remote.tvwoonkamer', 'current_activity') }}"
    trash_restafval_date:
      friendly_name: 'Grijze bak'
      value_template: '{{ as_timestamp(states.sensor.trash_restafval.state) | timestamp_custom("%Y-%m-%d") }}'
    studeertemp:
      friendly_name: 'StudeerTemp'     
      value_template: "{{ state_attr('climate.thermostaat_studeerkamer', 'temperature') }}"  
      unit_of_measurement: 'degrees'      

- platform: ring
  
vacuum:
  - platform: xiaomi_miio
    host: 192.168.178.60
    token: !secret token
    name: frits




      
