- platform: group
  name: alle lampen
  entities:
    #woonkamer
    - light.bloom
    - light.bank
    - light.go
    - light.eettafel
    - light.spetter
    - light.keuken
    #gangen
    - light.lamp_gang_boven
    - light.lamp_gang_beneden
    #wc
    - light.lamp_wc
    #noell
    - light.lamp_noell
    #remi
    - light.lamp_remi
    #slaapkamer
    - light.lamp_slaapkamer
    - light.lamp_nacht_jordi
    - light.lamp_nacht_iris
    #studeerkamer
    - light.lamp_studeerkamer
    #badkamer
    - light.lamp_badkamer_1
    - light.lamp_badkamer_2
    - light.lamp_badkamer_3
      
- platform: group
  name: Woonkamergroep
  entities:
    - light.bloom
    - light.bank
    - light.go
    - light.eettafel
    - light.spetter
    - light.keuken
    
- platform: group
  name: Slaapkamergroep
  entities:
    - light.lamp_plafond_slaapkamer
    - light.lamp_nacht_jordi
    - light.lamp_nacht_iris