- platform: group
  name: alle lampen
  entities:
    #woonkamer
    - light.lamp_bloom
    - light.lamp_bank
    - light.lamp_go
    - light.lamp_eettafel
    - light.lamp_spetter
    - light.lamp_keuken
    #gangen
    - light.lamp_gang_boven
    - light.lamp_gang_beneden
    #wc
    - light.lamp_wc
    #noell
    - light.lamp_noell
    #remi
    - light.lamp_remi
    #slaapkamer
    - light.lamp_slaapkamer
    - light.lamp_nacht_jordi
    - light.lamp_nacht_iris
    #studeerkamer
    - light.lamp_studeerkamer
    #badkamer
    - light.lamp_badkamer_1
    - light.lamp_badkamer_2
    - light.lamp_badkamer_3
      
- platform: group
  name: Woonkamergroep
  entities:
    - light.lamp_bloom
    - light.lamp_bank
    - light.lamp_go
    - light.lamp_eettafel
    - light.lamp_spetter
    - light.lamp_keuken
    
- platform: group
  name: Slaapkamergroep
  entities:
    - light.lamp_plafond_slaapkamer
    - light.lamp_nacht_jordi
    - light.lamp_nacht_iris