resources:
  - url: /community_plugin/banner-card/banner-card.js
    type: module
  - url: /community_plugin/mini-media-player/mini-media-player-bundle.js
    type: module
  - url: /community_plugin/button-card/button-card.js
    type: module
  - url: /community_plugin/lovelace-xiaomi-vacuum-map-card/xiaomi-vacuum-map-card.js
    type: module  
  - url: /community_plugin/lovelace-xiaomi-vacuum-card/xiaomi-vacuum-card.js
    type: js    
  - url: /community_plugin/jukebox.js
    type: module    
  - url: /community_plugin/birthday.js
    type: js   
  - url: /community_plugin/lovelace-slider-entity-row/slider-entity-row.js
    type: module    
    

title: Cool en brander
views:
    # View tab title.
  - title: Algemeen
    cards:
      - type: picture-elements
        image: /local/jordiiris.png
        elements: 
          - type: state-label
            entity: device_tracker.life360_iris_braun
            style:
              top: 92%
              left: 10%
              color: white            
          - type: state-label
            entity: device_tracker.life360_jordi_de_geus
            style:
              top: 92%
              left: 60%
              color: white                   

      - type: weather-forecast
        entity: weather.huis

###################################################
#                                                 #
#                Ring BEL                         #
#                                                 #
###################################################

      - type: picture-glance
        title: Voordeur
        entities:
          - binary_sensor.ring_voordeur_ding
          - binary_sensor.ring_voordeur_motion
          - entity: sensor.ring_voordeur_battery
            show_state: true            
          - entity: sensor.ring_voordeur_last_activity
            show_state: true
          - entity: sensor.ring_voordeur_last_ding
            show_state: true          
            icon: mdi:bell
        camera_image: camera.voordeur  
        camera_view: live
        
      - type: map
        aspect_ratio: 16:9
        default_zoom: 20
        entities:
          - person.jordi_de_geus
          - person.iris_braun
          - zone.home
        
  - title: Woonkamer
    cards:
###################################################
#                                                 #
#                 WOONKAMER                       #
#                                                 #
###################################################

        
      - type: picture-elements
        image: /local/woonkamer.jpg
        elements:
          - type: state-icon
            icon: mdi:lightbulb-on-outline
            tap_action:
              action: toggle
            hold_action:
              action: more-info
            entity: light.woonkamergroep         
            style:
              top: 85%
              left: 5%
              color: white
          - type: state-icon
            icon: mdi:spotlight
            tap_action:
              action: toggle
            hold_action:
              action: more-info
            entity: switch.sonoff_10009d2097       
            style:
              top: 85%
              left: 15%
              color: white      
          - type: state-icon 
            entity: binary_sensor.woonkamer_sensor
            style:
              top: 85%
              left: 70%
              color: white               
          - type: state-icon 
            icon: mdi:home-thermometer
            entity: sensor.woonkamer_sensor
            style:
              top: 85%
              left: 80%
              color: white              
          - type: state-label
            entity: sensor.woonkamer_sensor
            style:
              top: 85%
              left: 90%
              color: white
              
      - type: entities
        entities:
          - entity: scene.woonkamer_warm
          - entity: scene.woonkamer_helder
          - entity: scene.woonkamer_heel_warm

      - entity: media_player.woonkamer
        type: custom:mini-media-player
        #type: media-control
        artwork: cover
        source: icon    
        shortcuts: buttons
      - type: sensor
        entity: sensor.woonkamer_tv
        name: Activiteit Harmony  
        
      - type: entities
        entities:
          - type: custom:slider-entity-row
            entity: climate.spzb0001
            min: 7
            max: 30
            step: 0.5
      
      - type: gauge
        entity: sensor.woonkamerthermtemp_current
        name: Thermostaat
        unit: '*'
        min: 10
        max: 30
        severity:
          green: 20
          yellow: 27
          red: 30


  - title: Themostaat
    cards:
      - type: thermostat
        entity: climate.spzb0001     
###################################################
#                                                 #
#                STUDEERKAMER                     #
#                                                 #
###################################################

  - title: Overige kamers
    cards:
      - type: picture-elements
        image: /local/studeerkamer.jpg
        name: Studeerkamer
        elements:
          - type: state-icon
            icon: mdi:lightbulb-on-outline
            tap_action:
              action: toggle
            hold_action:
              action: more-info
            entity: light.lamp_studeerkamer    
            style:
              top: 85%
              left: 5%
              color: white  
          - type: state-icon 
            entity: binary_sensor.studeer_tradfri_bewegingssensor
            style:
              top: 85%
              left: 90%
              color: white               
          # - type: state-icon 
            # icon: mdi:home-thermometer
            # entity: climate.thermostaat_studeerkamer
            # style:
              # top: 85%
              # left: 80%
              # color: white              
          # - type: state-label
            # entity: climate.thermostaat_studeerkamer
            # style:
              # top: 85%
              # left: 90%
              # color: white                    
###################################################
#                                                 #
#                GANG BENEDEN                     #
#                                                 #
###################################################
      - type: picture-elements
        image: /local/gangb.jpg
        elements:
          - type: state-icon
            icon: mdi:lightbulb-on-outline
            tap_action:
              action: toggle
            hold_action:
              action: more-info
            entity: light.lamp_gang_beneden    
            style:
              top: 85%
              left: 5%
              color: white      
          - type: state-icon 
            entity: binary_sensor.gang_beneden_sensor
            style:
              top: 85%
              left: 15%
              color: white               
          - type: state-icon 
            icon: mdi:home-thermometer
            entity: sensor.gang_beneden_sensor
            style:
              top: 85%
              left: 25%
              color: white              
          - type: state-label
            entity: sensor.gang_beneden_sensor
            style:
              top: 85%
              left: 35%
              color: white    
#wc              
          - type: state-icon
            icon: mdi:lightbulb-on-outline
            tap_action:
              action: toggle
            hold_action:
              action: more-info
            entity: light.lamp_wc     
            style:
              top: 85%
              left: 60%
              color: white      
          - type: state-icon 
            entity: binary_sensor.wc_beneden
            style:
              top: 85%
              left: 70%
              color: white               
          - type: state-icon 
            icon: mdi:home-thermometer
            entity: sensor.wc_beneden
            style:
              top: 85%
              left: 80%
              color: white              
          - type: state-label
            entity: sensor.wc_beneden
            style:
              top: 85%
              left: 90%
              color: white               
###################################################
#                                                 #
#                SLAAPKAMER                       #
#                                                 #
###################################################
      - type: picture-elements
        image: /local/slaapk.jpg
        elements:
          - type: state-icon
            icon: mdi:lightbulb-on-outline
            tap_action:
              action: toggle
            hold_action:
              action: more-info
            entity: light.slaapkamer  
            style:
              top: 85%
              left: 15%
              color: white  
          - type: state-icon
            icon: mdi:ceiling-light
            tap_action:
              action: toggle
            hold_action:
              action: more-info
            entity: light.lamp_plafond_slaapkamer
            style:
              top: 85%
              left: 25%
              color: white   
          - type: state-icon
            icon: mdi:floor-lamp
            tap_action:
              action: toggle
            hold_action:
              action: more-info
            entity: light.lamp_nacht_jordi
            style:
              top: 85%
              left: 35%
              color: white  
          - type: state-icon
            icon: mdi:floor-lamp
            tap_action:
              action: toggle
            hold_action:
              action: more-info
            entity: light.lamp_nacht_iris
            style:
              top: 85%
              left: 45%
              color: white     
          - type: state-icon
            icon: mdi:power-socket-eu
            tap_action:
              action: toggle
            hold_action:
              action: more-info
            entity: switch.on_off_plug_in_unit_19
            style:
              top: 85%
              left: 95%
              color: white          
###################################################
#                                                 #
#                SLAAPKAMER                       #
#                                                 #
###################################################
      - type: picture-elements
        image: /local/douche.jpg
        elements:
          - type: state-icon
            icon: mdi:lightbulb-on-outline
            tap_action:
              action: toggle
            hold_action:
              action: more-info
            entity: light.lamp_gang_boven    
            style:
              top: 85%
              left: 5%
              color: white      
          - type: state-icon 
            entity: binary_sensor.gang_boven_sensor
            style:
              top: 85%
              left: 15%
              color: white               
          - type: state-icon 
            icon: mdi:home-thermometer
            entity: sensor.gang_boven_sensor_2
            style:
              top: 85%
              left: 25%
              color: white              
          - type: state-label
            entity: sensor.gang_boven_sensor_2
            style:
              top: 85%
              left: 35%
              color: white    
#wc              
          - type: state-icon
            icon: mdi:lightbulb-on-outline
            tap_action:
              action: toggle
            hold_action:
              action: more-info
            entity: light.badkamer    
            style:
              top: 85%
              left: 60%
              color: white      
          - type: state-icon 
            entity: binary_sensor.badkamer_sensor
            style:
              top: 85%
              left: 70%
              color: white               
          - type: state-icon 
            icon: mdi:home-thermometer
            entity: sensor.badkamer_sensor
            style:
              top: 85%
              left: 80%
              color: white              
          - type: state-label
            entity: sensor.badkamer_sensor
            style:
              top: 85%
              left: 90%
              color: white  
      - type: custom:jukebox-card
        links:
          - url: http://14923.live.streamtheworld.com:80/RADIO538AAC.aac
            name: 538          
          - url: https://icecast-qmusicnl-cdp.triple-it.nl/Qmusic_nl_live_96.mp3
            name: Q Music          
          - url: https://20403.live.streamtheworld.com/SRGSTR01.mp3?dist=sky-radio_web&ttag=talpa_consent:0
            name: Skyradio                                         
        entities:  
          - media_player.slaapkamer_mini
          - media_player.keuken_mini              

###################################################
#                                                 #
#                afvalwijzer                      #
#                                                 #
###################################################
              
  - title: Afval
    cards:
      - type: picture-elements
        image: /local/AFVAL.png
        elements:
          - type: state-label
            entity: sensor.trash_firstdate
            prefix: "Wordt opgehaald op: "
            style:
              top: 12%
              left: 40%
              color: green                 
          - type: state-label
            entity: sensor.trash_firstwastetype 
            style:
              top: 10%
              left: 68%
              color: blue 
          - type: state-label
            entity: sensor.trash_gft
            style:
              top: 22%
              left: 60%
              color: grey
              font-size: 30px
          - type: state-label
            entity: sensor.trash_papier
            style:
              top: 40%
              left: 60%
              color: grey
              font-size: 30px              
          - type: state-label
            entity: sensor.trash_restafval
            style:
              top: 58%
              left: 60%
              color: grey
              font-size: 30px   
          - type: state-label
            entity: sensor.trash_pmd
            style:
              top: 74%
              left: 60%
              color: grey
              font-size: 30px    
          - type: state-label
            entity: sensor.trash_grof_tuinafval
            style:
              top: 91%
              left: 60%
              color: grey
              font-size: 30px   

                   
### VACUUM


  - title: Stofzuiger
    cards:
      - type: custom:xiaomi-vacuum-card
        entity: vacuum.frits
        image: /local/vacuum.png
        name: Frits
        buttons: true
        labels:
          status: Status
          battery: Batterij
          mode: Mode
          main_brush: Hoofdborstel
          side_brush: Zijborstel
          filter: Filter
          sensor: Sensoren    
      - type: custom:xiaomi-vacuum-map-card
        entity: vacuum.frits
        map_image: '/local/map.png'
        calibration_points:
          - vacuum:
              x: 28500
              y: 25350
            map:
              x: 277
              y: 221
          - vacuum:
              x: 25300
              y: 21650
            map:
              x: 111
              y: 411
          - vacuum:
              x: 33200
              y: 20800
            map:
              x: 518
              y: 454
        zones:
          - [[23280,23666,27980,26516,1],[25395,21121,32595,25871,1],[32450,20049,33350,22849,1],[30853,25824,33653,29274,1]]
          
  - title: Data
    cards:
      - type: "custom:day-countdown"
        date: "25 dec 2019"  
        title: Kerst
        icon_url: https://en.wikipedia.org/wiki/July_16      
      - type: "custom:day-countdown"
        date: "1 jan 2020"  
        title: Iris verjaardag
        icon_url: https://en.wikipedia.org/wiki/July_16        

       